-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS actors CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS films_actors CASCADE;
DROP TABLE IF EXISTS films_categories CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP SEQUENCE IF EXISTS public.actors_actor_id_seq;
DROP SEQUENCE IF EXISTS public.addresses_address_id_seq;
DROP SEQUENCE IF EXISTS public.categories_category_id_seq;
DROP SEQUENCE IF EXISTS public.cities_city_id_seq;
DROP SEQUENCE IF EXISTS public.countries_country_id_seq;
DROP SEQUENCE IF EXISTS public.customers_customer_id_seq;
DROP SEQUENCE IF EXISTS public.employees_employee_id_seq;
DROP SEQUENCE IF EXISTS public.films_film_id_seq;
DROP SEQUENCE IF EXISTS public.inventory_inventory_id_seq;
DROP SEQUENCE IF EXISTS public.languages_language_id_seq;
DROP SEQUENCE IF EXISTS public.payments_payment_id_seq;
DROP SEQUENCE IF EXISTS public.rentals_rental_id_seq;
DROP SEQUENCE IF EXISTS public.stores_store_id_seq;
